# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notelyGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import rsc1


class Ui_Logged_in_window(object):
    def setupUi(self, Logged_in_window):
        Logged_in_window.setObjectName("Logged_in_window")
        Logged_in_window.resize(800, 666)
        self.centralwidget = QtWidgets.QWidget(Logged_in_window)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 666))
        self.stackedWidget.setObjectName("stackedWidget")
        self.signup_page = QtWidgets.QWidget()
        self.signup_page.setObjectName("signup_page")
        self.graphicsView = QtWidgets.QGraphicsView(self.signup_page)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 800, 666))
        self.graphicsView.setStyleSheet("background-image: url(:/newPrefix/backgnd.jpeg);")
        self.graphicsView.setObjectName("graphicsView")
        self.splitter = QtWidgets.QSplitter(self.signup_page)
        self.splitter.setGeometry(QtCore.QRect(590, 276, 160, 120))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(40)
        self.splitter.setObjectName("splitter")
        self.sign_up_btn = QtWidgets.QPushButton(self.splitter)
        self.sign_up_btn.setObjectName("sign_up_btn")
        self.back_btn = QtWidgets.QPushButton(self.splitter)
        self.back_btn.setObjectName("back_btn")
        self.splitter_2 = QtWidgets.QSplitter(self.signup_page)
        self.splitter_2.setGeometry(QtCore.QRect(220, 180, 221, 291))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(20)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.line_first_name = QtWidgets.QLineEdit(self.splitter_3)
        self.line_first_name.setStyleSheet("background-color: rgb(255, 211, 33);\n"
"alternate-background-color: rgb(255, 211, 33);")
        self.line_first_name.setAlignment(QtCore.Qt.AlignCenter)
        self.line_first_name.setObjectName("line_first_name")
        self.line_last_name = QtWidgets.QLineEdit(self.splitter_3)
        self.line_last_name.setStyleSheet("background-color: rgb(255, 211, 33);\n"
"alternate-background-color: rgb(255, 211, 33);")
        self.line_last_name.setAlignment(QtCore.Qt.AlignCenter)
        self.line_last_name.setObjectName("line_last_name")
        self.line_email = QtWidgets.QLineEdit(self.splitter_3)
        self.line_email.setStyleSheet("background-color: rgb(255, 211, 33);\n"
"alternate-background-color: rgb(255, 211, 33);")
        self.line_email.setAlignment(QtCore.Qt.AlignCenter)
        self.line_email.setObjectName("line_email")
        self.line_user = QtWidgets.QLineEdit(self.splitter_3)
        self.line_user.setStyleSheet("background-color: rgb(255, 211, 33);\n"
"alternate-background-color: rgb(255, 211, 33);")
        self.line_user.setAlignment(QtCore.Qt.AlignCenter)
        self.line_user.setObjectName("line_user")
        self.line_pass = QtWidgets.QLineEdit(self.splitter_3)
        self.line_pass.setStyleSheet("background-color: rgb(255, 211, 33);\n"
"alternate-background-color: rgb(255, 211, 33);")
        self.line_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass.setAlignment(QtCore.Qt.AlignCenter)
        self.line_pass.setObjectName("line_pass")
        self.stackedWidget.addWidget(self.signup_page)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.splitter_4 = QtWidgets.QSplitter(self.login_page)
        self.splitter_4.setGeometry(QtCore.QRect(220, 238, 220, 190))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setHandleWidth(6)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setHandleWidth(40)
        self.splitter_5.setObjectName("splitter_5")
        self.line_user_2 = QtWidgets.QLineEdit(self.splitter_5)
        self.line_user_2.setStyleSheet("background-color: rgb(255, 211, 33);\n"
"alternate-background-color: rgb(255, 211, 33);")
        self.line_user_2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_user_2.setObjectName("line_user_2")
        self.line_pass_2 = QtWidgets.QLineEdit(self.splitter_5)
        self.line_pass_2.setStyleSheet("background-color: rgb(255, 211, 33);\n"
"alternate-background-color: rgb(255, 211, 33);")
        self.line_pass_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass_2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_pass_2.setObjectName("line_pass_2")
        self.splitter_6 = QtWidgets.QSplitter(self.login_page)
        self.splitter_6.setGeometry(QtCore.QRect(590, 276, 160, 120))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setHandleWidth(40)
        self.splitter_6.setObjectName("splitter_6")
        self.log_in_btn = QtWidgets.QPushButton(self.splitter_6)
        self.log_in_btn.setObjectName("log_in_btn")
        self.back_btn_2 = QtWidgets.QPushButton(self.splitter_6)
        self.back_btn_2.setObjectName("back_btn_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.login_page)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 0, 800, 666))
        self.graphicsView_2.setStyleSheet("background-image: url(:/newPrefix/backgnd.jpeg);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_2.raise_()
        self.splitter_6.raise_()
        self.splitter_4.raise_()
        self.stackedWidget.addWidget(self.login_page)
        self.main_menu_page = QtWidgets.QWidget()
        self.main_menu_page.setObjectName("main_menu_page")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.main_menu_page)
        self.graphicsView_3.setGeometry(QtCore.QRect(0, 0, 800, 666))
        self.graphicsView_3.setStyleSheet("background-image: url(:/newPrefix/backgnd.jpeg);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.splitter_7 = QtWidgets.QSplitter(self.main_menu_page)
        self.splitter_7.setGeometry(QtCore.QRect(576, 183, 160, 300))
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setHandleWidth(20)
        self.splitter_7.setObjectName("splitter_7")
        self.new_note_btn = QtWidgets.QPushButton(self.splitter_7)
        self.new_note_btn.setObjectName("new_note_btn")
        self.new_cat_btn = QtWidgets.QPushButton(self.splitter_7)
        self.new_cat_btn.setObjectName("new_cat_btn")
        self.list_cat_btn = QtWidgets.QPushButton(self.splitter_7)
        self.list_cat_btn.setObjectName("list_cat_btn")
        self.gen_cat_btn = QtWidgets.QPushButton(self.splitter_7)
        self.gen_cat_btn.setObjectName("gen_cat_btn")
        self.log_out_btn = QtWidgets.QPushButton(self.splitter_7)
        self.log_out_btn.setObjectName("log_out_btn")
        self.stackedWidget.addWidget(self.main_menu_page)
        self.new_note_page = QtWidgets.QWidget()
        self.new_note_page.setObjectName("new_note_page")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.new_note_page)
        self.graphicsView_4.setGeometry(QtCore.QRect(0, 0, 800, 666))
        self.graphicsView_4.setStyleSheet("background-image: url(:/newPrefix/backgnd.jpeg);")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.splitter_8 = QtWidgets.QSplitter(self.new_note_page)
        self.splitter_8.setGeometry(QtCore.QRect(540, 120, 221, 401))
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setHandleWidth(40)
        self.splitter_8.setObjectName("splitter_8")
        self.cat_note_lbl = QtWidgets.QLabel(self.splitter_8)
        self.cat_note_lbl.setObjectName("cat_note_lbl")
        self.reminder_dt = QtWidgets.QDateTimeEdit(self.splitter_8)
        self.reminder_dt.setObjectName("reminder_dt")
        self.reminder_chkbx = QtWidgets.QCheckBox(self.splitter_8)
        self.reminder_chkbx.setObjectName("reminder_chkbx")
        self.save_note_btn = QtWidgets.QPushButton(self.splitter_8)
        self.save_note_btn.setObjectName("save_note_btn")
        self.discard_note_btn = QtWidgets.QPushButton(self.splitter_8)
        self.discard_note_btn.setObjectName("discard_note_btn")
        self.line_note_name = QtWidgets.QLineEdit(self.new_note_page)
        self.line_note_name.setGeometry(QtCore.QRect(200, 110, 251, 51))
        self.line_note_name.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.line_note_name.setStyleSheet("background-color: rgb(255, 211, 33);\n"
"alternate-background-color: rgb(255, 211, 33);")
        self.line_note_name.setInputMask("")
        self.line_note_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_note_name.setAlignment(QtCore.Qt.AlignCenter)
        self.line_note_name.setObjectName("line_note_name")
        self.note_data_txt = QtWidgets.QTextEdit(self.new_note_page)
        self.note_data_txt.setGeometry(QtCore.QRect(200, 170, 251, 381))
        font = QtGui.QFont()
        font.setFamily("URW Chancery L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.note_data_txt.setFont(font)
        self.note_data_txt.setStyleSheet("background-color: rgb(255, 211, 33, 0);\n"
"border-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 0, 0);\n"
"alternate-background-color: rgb(255, 211, 33, 0);\n"
"border-top-color: rgb(255, 0, 0);\n"
"gridline-color: rgb(255, 0, 0);\n"
"")
        self.note_data_txt.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.note_data_txt.setObjectName("note_data_txt")
        self.stackedWidget.addWidget(self.new_note_page)
        self.update_note_page = QtWidgets.QWidget()
        self.update_note_page.setObjectName("update_note_page")
        self.splitter_11 = QtWidgets.QSplitter(self.update_note_page)
        self.splitter_11.setGeometry(QtCore.QRect(540, 120, 221, 401))
        self.splitter_11.setOrientation(QtCore.Qt.Vertical)
        self.splitter_11.setHandleWidth(40)
        self.splitter_11.setObjectName("splitter_11")
        self.cat_note_lbl_2 = QtWidgets.QLabel(self.splitter_11)
        self.cat_note_lbl_2.setObjectName("cat_note_lbl_2")
        self.reminder_dt_2 = QtWidgets.QDateTimeEdit(self.splitter_11)
        self.reminder_dt_2.setObjectName("reminder_dt_2")
        self.reminder_chkbx_2 = QtWidgets.QCheckBox(self.splitter_11)
        self.reminder_chkbx_2.setObjectName("reminder_chkbx_2")
        self.updat_note_btn = QtWidgets.QPushButton(self.splitter_11)
        self.updat_note_btn.setObjectName("updat_note_btn")
        self.delete_note_btn = QtWidgets.QPushButton(self.splitter_11)
        self.delete_note_btn.setObjectName("delete_note_btn")
        self.go_back_btn_3 = QtWidgets.QPushButton(self.splitter_11)
        self.go_back_btn_3.setObjectName("go_back_btn_3")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.update_note_page)
        self.graphicsView_7.setGeometry(QtCore.QRect(0, 0, 800, 666))
        self.graphicsView_7.setStyleSheet("background-image: url(:/newPrefix/backgnd.jpeg);")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.line_note_name_2 = QtWidgets.QLineEdit(self.update_note_page)
        self.line_note_name_2.setGeometry(QtCore.QRect(200, 110, 251, 51))
        self.line_note_name_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.line_note_name_2.setStyleSheet("background-color: rgb(255, 211, 33);\n"
"alternate-background-color: rgb(255, 211, 33);")
        self.line_note_name_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_note_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.line_note_name_2.setObjectName("line_note_name_2")
        self.note_data_txt_2 = QtWidgets.QTextEdit(self.update_note_page)
        self.note_data_txt_2.setGeometry(QtCore.QRect(200, 170, 251, 381))
        font = QtGui.QFont()
        font.setFamily("URW Chancery L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.note_data_txt_2.setFont(font)
        self.note_data_txt_2.setStyleSheet("background-color: rgb(255, 211, 33, 0);\n"
"border-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 0, 0);\n"
"alternate-background-color: rgb(255, 211, 33, 0);\n"
"border-top-color: rgb(255, 0, 0);\n"
"gridline-color: rgb(255, 0, 0);\n"
"")
        self.note_data_txt_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.note_data_txt_2.setObjectName("note_data_txt_2")
        self.graphicsView_7.raise_()
        self.splitter_11.raise_()
        self.line_note_name_2.raise_()
        self.note_data_txt_2.raise_()
        self.stackedWidget.addWidget(self.update_note_page)
        self.new_cat_page = QtWidgets.QWidget()
        self.new_cat_page.setObjectName("new_cat_page")
        self.new_cat_txt = QtWidgets.QLineEdit(self.new_cat_page)
        self.new_cat_txt.setGeometry(QtCore.QRect(200, 318, 251, 50))
        self.new_cat_txt.setStyleSheet("background-color: rgb(255, 211, 33);\n"
"alternate-background-color: rgb(255, 211, 33);")
        self.new_cat_txt.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.new_cat_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.new_cat_txt.setObjectName("new_cat_txt")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.new_cat_page)
        self.graphicsView_5.setGeometry(QtCore.QRect(0, 0, 800, 666))
        self.graphicsView_5.setStyleSheet("background-image: url(:/newPrefix/backgnd.jpeg);")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.splitter_9 = QtWidgets.QSplitter(self.new_cat_page)
        self.splitter_9.setGeometry(QtCore.QRect(550, 250, 221, 166))
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setHandleWidth(50)
        self.splitter_9.setObjectName("splitter_9")
        self.add_cat_btn = QtWidgets.QPushButton(self.splitter_9)
        self.add_cat_btn.setObjectName("add_cat_btn")
        self.go_bck_btn = QtWidgets.QPushButton(self.splitter_9)
        self.go_bck_btn.setObjectName("go_bck_btn")
        self.graphicsView_5.raise_()
        self.splitter_9.raise_()
        self.new_cat_txt.raise_()
        self.note_data_txt.raise_()
        self.stackedWidget.addWidget(self.new_cat_page)
        self.list_note_cat_page = QtWidgets.QWidget()
        self.list_note_cat_page.setObjectName("list_note_cat_page")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.list_note_cat_page)
        self.graphicsView_6.setGeometry(QtCore.QRect(0, 0, 800, 666))
        self.graphicsView_6.setStyleSheet("background-image: url(:/newPrefix/backgnd.jpeg);")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.scrollArea = QtWidgets.QScrollArea(self.list_note_cat_page)
        self.scrollArea.setGeometry(QtCore.QRect(190, 110, 281, 451))
        self.scrollArea.setStyleSheet("background-color: rgb(255, 220, 44, 0);")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 281, 451))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.splitter_10 = QtWidgets.QSplitter(self.list_note_cat_page)
        self.splitter_10.setGeometry(QtCore.QRect(576, 220, 141, 226))
        self.splitter_10.setOrientation(QtCore.Qt.Vertical)
        self.splitter_10.setHandleWidth(40)
        self.splitter_10.setObjectName("splitter_10")
        self.cat_name_lbl = QtWidgets.QLabel(self.splitter_10)
        self.cat_name_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.cat_name_lbl.setObjectName("cat_name_lbl")
        self.new_note_cat_btn = QtWidgets.QPushButton(self.splitter_10)
        self.new_note_cat_btn.setObjectName("new_note_cat_btn")
        self.go_back_btn_2 = QtWidgets.QPushButton(self.splitter_10)
        self.go_back_btn_2.setObjectName("go_back_btn_2")
        self.graphicsView_6.raise_()
        self.splitter_10.raise_()
        self.scrollArea.raise_()
        self.stackedWidget.addWidget(self.list_note_cat_page)
        self.list_all_cat_page = QtWidgets.QWidget()
        self.list_all_cat_page.setObjectName("list_all_cat_page")
        self.splitter_12 = QtWidgets.QSplitter(self.list_all_cat_page)
        self.splitter_12.setGeometry(QtCore.QRect(576, 245, 141, 176))
        self.splitter_12.setOrientation(QtCore.Qt.Vertical)
        self.splitter_12.setHandleWidth(40)
        self.splitter_12.setObjectName("splitter_12")
        self.delete_cat_btn = QtWidgets.QPushButton(self.splitter_12)
        self.delete_cat_btn.setObjectName("delete_cat_btn")
        self.go_back_btn_4 = QtWidgets.QPushButton(self.splitter_12)
        self.go_back_btn_4.setObjectName("go_back_btn_4")
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.list_all_cat_page)
        self.graphicsView_8.setGeometry(QtCore.QRect(0, 0, 800, 666))
        self.graphicsView_8.setStyleSheet("background-image: url(:/newPrefix/backgnd.jpeg);")
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.list_all_cat_page)
        self.scrollArea_2.setGeometry(QtCore.QRect(190, 110, 281, 451))
        self.scrollArea_2.setStyleSheet("background-color: rgb(255, 220, 44, 0);")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 281, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.splitter_12.raise_()
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.graphicsView_8.raise_()
        self.splitter_12.raise_()
        self.scrollArea_2.raise_()
        self.stackedWidget.addWidget(self.list_all_cat_page)
        Logged_in_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Logged_in_window)
        self.stackedWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(Logged_in_window)

    def retranslateUi(self, Logged_in_window):
        _translate = QtCore.QCoreApplication.translate
        Logged_in_window.setWindowTitle(_translate("Logged_in_window", "NoteLY - The Web Server Based Online Notebook"))
        self.sign_up_btn.setText(_translate("Logged_in_window", "Register"))
        self.back_btn.setText(_translate("Logged_in_window", "Go Back"))
        self.line_first_name.setPlaceholderText(_translate("Logged_in_window", "First Name"))
        self.line_last_name.setPlaceholderText(_translate("Logged_in_window", "Last name"))
        self.line_email.setPlaceholderText(_translate("Logged_in_window", "Email"))
        self.line_user.setPlaceholderText(_translate("Logged_in_window", "Username"))
        self.line_pass.setPlaceholderText(_translate("Logged_in_window", "Password"))
        self.line_user_2.setPlaceholderText(_translate("Logged_in_window", "Username"))
        self.line_pass_2.setPlaceholderText(_translate("Logged_in_window", "Password"))
        self.log_in_btn.setText(_translate("Logged_in_window", "Login"))
        self.back_btn_2.setText(_translate("Logged_in_window", "Go Back"))
        self.new_note_btn.setText(_translate("Logged_in_window", "Make a new note"))
        self.new_cat_btn.setText(_translate("Logged_in_window", "Make a new category"))
        self.list_cat_btn.setText(_translate("Logged_in_window", "See all categories"))
        self.gen_cat_btn.setText(_translate("Logged_in_window", "Uncategorized notes"))
        self.log_out_btn.setText(_translate("Logged_in_window", "Logout"))
        self.cat_note_lbl.setText(_translate("Logged_in_window", "Category:"))
        self.reminder_chkbx.setText(_translate("Logged_in_window", "Reminder"))
        self.save_note_btn.setText(_translate("Logged_in_window", "Save Note"))
        self.discard_note_btn.setText(_translate("Logged_in_window", "Discard Note"))
        self.line_note_name.setPlaceholderText(_translate("Logged_in_window", "Note name"))
        self.note_data_txt.setHtml(_translate("Logged_in_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'URW Chancery L\'; font-size:16pt; font-weight:600; font-style:italic;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.cat_note_lbl_2.setText(_translate("Logged_in_window", "Category:"))
        self.reminder_chkbx_2.setText(_translate("Logged_in_window", "Reminder"))
        self.updat_note_btn.setText(_translate("Logged_in_window", "Update Note"))
        self.delete_note_btn.setText(_translate("Logged_in_window", "Delete Note"))
        self.go_back_btn_3.setText(_translate("Logged_in_window", "Go Back"))
        self.line_note_name_2.setPlaceholderText(_translate("Logged_in_window", "Note name"))
        self.note_data_txt_2.setHtml(_translate("Logged_in_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'URW Chancery L\'; font-size:16pt; font-weight:600; font-style:italic;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.new_cat_txt.setPlaceholderText(_translate("Logged_in_window", "New Category Name"))
        self.add_cat_btn.setText(_translate("Logged_in_window", "Add Category"))
        self.go_bck_btn.setText(_translate("Logged_in_window", "Go Back"))
        self.cat_name_lbl.setText(_translate("Logged_in_window", "Categoty"))
        self.new_note_cat_btn.setText(_translate("Logged_in_window", "New Note"))
        self.go_back_btn_2.setText(_translate("Logged_in_window", "Go Back"))
        self.delete_cat_btn.setText(_translate("Logged_in_window", "Delete Category(s)"))
        self.go_back_btn_4.setText(_translate("Logged_in_window", "Go Back"))
